services:
  api:
    image: app/otp
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - default
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
